name: bank_vault
description: A web app that uses AngularDart Components
# version: 1.0.0
# homepage: https://www.example.com
# author: WebSter <email@example.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  angular: ^5.1.0
  angular_components: ^0.10.1
  angular_forms: ^2.0.0
  angular_router: ^2.0.0-alpha+19
  http: ^0.12.0
  dialog: ^0.7.0

dev_dependencies:
  angular_test: ^2.1.0
  build_runner: ^1.1.2
  build_test: ^0.10.3
  build_web_compilers: ^0.4.4
  test: ^1.5.1
